services:
  nextjs:
    container_name: nextjs-starterd
    image: nextjs-starter:latest
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./ci/Dockerfile
    ports:
      - '19300:3000'
    environment:
      - NODE_ENV=production
