name: deploy test nextjs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy with Podman
        run: |
          # Build the image
          podman build -t nextjs-starter:latest -f ci/Dockerfile .
          
          # Stop existing pod if running
          podman kube down ci/nextjs-starter.kube || true
          
          # Deploy with podman kube and register as systemd service
          podman kube play ci/nextjs-starter.kube --service-type=systemd
          
          # Enable and start the service
          systemctl --user enable --now pod-nextjs-starter.service
