name: deploy test nextjs

on:
  push:
    branches:
      - gh

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to the Docker registry
        run: echo "Logging in is not needed since we are using local Docker registry"

      - name: Build and run Docker container
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d
