name: deploy test nextjs

on:
  push:
    branches:
      - gh
      - release
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Build and run Docker container
        run: |
          cd ci
          docker-compose up -d --build --force-recreate --remove-orphans
