name: deploy test nextjs

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy with Podman
        run: |
          cd ci
          docker compose up -d --build --force-recreate
